### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by dennexequiel** [abpilot/abpilot.com#1]
Create a home page for AB Pilot.

**Comment by UditNS** [comment]
Hi @dennexequiel, I wan to work on this and tell me something about AB Pilot.

**Comment by dennexequiel** [comment]
Hi @UditNS,

AB Pilot aims to make split testing easy. This tool can be used by content creators, developers, etc., and have the public choose what content is more appealing by upvoting. Also, we're planning to provide an open API and embeddable components for developers.

For the front-end tech stack tailwind is our preference.

**Comment by UditNS** [comment]
I will work on it.

**Comment by dennexequiel** [comment]
> I will work on it.

Thanks! I'm looking forward to it.

**Comment by UditNS** [comment]
Hi, I have complete the homepage but I am not able to push to my remote repository

**Comment by dennexequiel** [comment]
Thank you, @UditNS, PR #3 was merged.
