### ISSUE TITLE
button hover color issue

### ISSUE THREAD

**Issue by YSanj98** [abpilot/abpilot.com#13]
Hi. I saw an issue. 
when hover the button Get Started in home page, bg color convert to white. but text color white too. i would like to make a PR for fix this issue.

**Comment by dennexequiel** [comment]
Thanks for your contribution. This has been merged into main:
https://github.com/abpilot/abpilot.com/pull/12

**Comment by YSanj98** [comment]
@dennexequiel you're welcome and glad to contribute this project. 
I realized every button has that hover issue, not only in the Get Started button in home page. I made a PR after fixing that issue.
